#######################################################################
#                                                                     #
#          Array Practice Core - Developed By Drizzy#0278             #
#       Bought at Refine Development - https://dsc.gg/refine          #
#                                                                     #
#######################################################################
LICENSE: ""

MONGO:
  URI-MODE: true
  NORMAL:
    HOST: 127.0.0.1
    PORT: 27017
    DATABASE: Array
    AUTHENTICATION:
      ENABLED: false
      USERNAME: ''
      PASSWORD: ''
  URI:
    DATABASE: Array
    CONNECTION_STRING: mongodb://127.0.0.1:27017/Array

SETTINGS:
  SPAWN: world:0:60.0:0:0.0:0.0
  CORE_HOOK: true
  HCF_ENABLED: true
  TAB_ENABLED: true
  FFA_CIRCLE_RADIUS: 10
  TELEPORT_DELAY: 4
  ARENA_RATING: true
  BRIDGE_CLEARBLOCKS: true
  REMOVE_BOTTLES: true
  DISCLAIMER_MESSAGE_ENABLED: true

JOIN_MESSAGE:
  ENABLED: true
  MESSAGE:
    - ""
    - "&c&lArray &7&l| &fPractice &7(EU)"
    - "&7Welcome to the &cTest Server &7of &cArray Practice&7."
    - ""
    - "&7Purchase Array at &chttps://dsc.gg/refine&7."
    - "&7Engage with our community at &cdsc.gg/purge&7."
    - ""

QUEUE_LORE:
  - "&7&m------------------------"
  - "&7* &fIn Queue: &c<in_queue>"
  - "&7* &fIn Fight: &c<in_fight>"
  - ""
  - "&fClick to join queue"
  - "&7&m------------------------"

#In Seconds
COOLDOWNS:
  ENDER_PEARL: 15
  BOW: 10

MATCH:
  SPAWN_YLEVEL_ADD: 6
  START_COUNTDOWN: 3
  COUNTDOWN_SOUND: NOTE_STICKS
  STARTED_SOUND: NOTE_BASS
  TITLE:
    STARTED:
      ENABLED: true
      TEXT: "&aMatch Started"
      SUB_TEXT: ""
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5
    COUNTDOWN:
      ENABLED: true
      TEXT: "&7Starting in &c<seconds>"
      SUB_TEXT: ""
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5
    WINNER:
      ENABLED: true
      TEXT: "&aWINNER"
      SUB_TEXT: "&7Good Game!"
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5
    LOSER:
      ENABLED: true
      TEXT: "&cLOSER!"
      SUB_TEXT: "&7Better Luck next time!"
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5

SOCIAL:
  DISCORD: discord.link/purge
  STORE: store.purgecommunity.com
  WEBSITE: www.purgecommunity.com
  TWITTER: '@PurgeCommunity'

RANKED:
  ENABLED: true
  REQUIREKILLS: true
  REQUIREDKILLS: 10
  LIMIT_PING: true
  PING-LIMIT: 300

NAMETAGS:
  ENABLED: true
  DEFAULT: <rank_color>
  PARTY: BLUE
  EVENT: AQUA

UPDATE_NOTIFICATION: true