#######################################################################
#                                                                     #
#          Array Practice Core - Developed By Drizzy#0278             #
#       Bought at Refine Development - https://dsc.gg/refine          #
#                                                                     #
#######################################################################
LICENSE: ""

MONGO:
  URI-MODE: true
  NORMAL:
    HOST: 127.0.0.1
    PORT: 27017
    DATABASE: Array
    AUTHENTICATION:
      ENABLED: false
      USERNAME: ''
      PASSWORD: ''
  URI:
    DATABASE: Array
    CONNECTION_STRING: mongodb://127.0.0.1:27017/Array

SETTINGS:
  SPAWN: world:0:60.0:0:0.0:0.0
  CORE_HOOK: true
  HCF_ENABLED: true
  TAB_ENABLED: true
  FFA_CIRCLE_RADIUS: 10
  TELEPORT_DELAY: 4
  ARENA_RATING: true
  REMOVE_BOTTLES: true
  DISCLAIMER_MESSAGE_ENABLED: true

JOIN_MESSAGE:
  ENABLED: true
  MESSAGE:
    - ""
    - "&c&lArray &7&l| &fPractice &7(EU)"
    - "&7Welcome to the &cTest Server &7of &cArray Practice&7."
    - ""
    - "&7Purchase Array at &chttps://dsc.gg/refine&7."
    - "&7Engage with our community at &cdsc.gg/purge&7."
    - ""

QUEUE_LORE:
  - "&7&m------------------------"
  - "&7* &fIn Queue: &c<in_queue>"
  - "&7* &fIn Fight: &c<in_fight>"
  - ""
  - "&fClick to join queue"
  - "&7&m------------------------"

#In Seconds
COOLDOWNS:
  ENDER_PEARL: 15
  BOW: 10

MATCH:
  SPAWN_YLEVEL_ADD: 6
  COUNTDOWN_INTERVAL: 3
  THEBRIDGE_CLEARBLOCKS: true
  COUNTDOWN_SOUND: NOTE_STICKS
  STARTED_SOUND: NOTE_BASS
  TITLE:
    STARTED:
      ENABLED: true
      TEXT: "&aMatch Started"
      SUB_TEXT: ""
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5
    COUNTDOWN:
      ENABLED: true
      TEXT: "&7Starting in &c<seconds>"
      SUB_TEXT: ""
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5
    WINNER:
      ENABLED: true
      TEXT: "&aWINNER"
      SUB_TEXT: "&7Good Game!"
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5
    LOSER:
      ENABLED: true
      TEXT: "&cLOSER!"
      SUB_TEXT: "&7Better Luck next time!"
      FADE_IN: 5
      STAY: 20
      FADE_OUT: 5

SOCIAL:
  DISCORD: discord.gg/refine
  STORE: store.refinedev.xyz
  WEBSITE: www.refinedev.xyz
  TWITTER: '@RefineDev'

RANKED:
  ENABLED: true
  REQUIREKILLS: true
  REQUIREDKILLS: 10
  LIMIT_PING: true
  PING-LIMIT: 300

NAMETAGS:
  ENABLED: true
  DEFAULT: <rank_color>
  PARTY: BLUE
  EVENT: AQUA

DIVISIONS:
   ENABLED: true
   #If set to false, the division will be based on elo
   #and XP will be turned off completely as it won't have any purpose
   XP_BASED: false
   RANKS:
     SILVER_1:
       Display_Name: "&7Silver I"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 0
       XP-LEVEL: 1
     SILVER_2:
       Display_Name: "&7Silver II"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 1000
       XP-LEVEL: 2
     SILVER_3:
       Display_Name: "&7Silver III"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 2000
       XP-LEVEL: 3
     SILVER_4:
       Display_Name: "&7Silver IV"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 3000
       XP-LEVEL: 4
     SILVER_5:
       Display_Name: "&7Silver V"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 4000
       XP-LEVEL: 5
     GOLD_1:
       Display_Name: "&6Gold I"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 5000
       XP-LEVEL: 6
     GOLD_2:
       Display_Name: "&6Gold II"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 7000
       XP-LEVEL: 7
     GOLD_3:
       Display_Name: "&6Gold III"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 8000
       XP-LEVEL: 8
     DIAMOND_1:
       Display_Name: "&bDiamond I"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 9000
       XP-LEVEL: 9
     DIAMOND_2:
       Display_Name: "&bDiamond II"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 10000
       XP-LEVEL: 10
     DIAMOND_3:
       Display_Name: "&bDiamond III"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 11000
       XP-LEVEL: 11
     EMERALD_1:
       Display_Name: "&aEmerald I"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 12000
       XP-LEVEL: 12
     EMERALD_2:
       Display_Name: "&aEmerald II"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 13000
       XP-LEVEL: 13
     EMERALD_3:
       Display_Name: "&aEmerald III"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 14000
       XP-LEVEL: 14
     EMERALD_4:
       Display_Name: "&aEmerald IV"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 16000
       XP-LEVEL: 15
     EMERALD_5:
       Display_Name: "&aEmerald V"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 20000
       XP-LEVEL: 16
     AMETHYST_1:
       Display_Name: "&2Amethyst I"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 24000
       XP-LEVEL: 17
     AMETHYST_2:
       Display_Name: "&2Amethyst II"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 26000
       XP-LEVEL: 18
     AMETHYST_3:
       Display_Name: "&2Amethyst III"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 36000
       XP-LEVEL: 19
     PLATINUM_1:
       Display_Name: "&ePlatinum I"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 46000
       XP-LEVEL: 20
     PLATINUM_2:
       Display_Name: "&ePlatinum II"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 56000
       XP-LEVEL: 21
     PLATINUM_3:
       Display_Name: "&ePlatinum III"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 76000
       XP-LEVEL: 22
     PLATINUM_4:
       Display_Name: "&ePlatinum IV"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 86000
       XP-LEVEL: 23
     PLATINUM_5:
       Display_Name: "&ePlatinum V"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 100000
       XP-LEVEL: 24
     MASTER:
       Display_Name: "&cMaster"
       ELO-Min: 0
       ELO-Max: 1000
       XP-AMOUNT: 200000
       XP-LEVEL: 25

UPDATE_NOTIFICATION: true