name: Legacy
main: xyz.refinedev.practice
authors: [Vifez, tmoa]
website: https://dsc.gg/cortex
version: 2.0
description: "Most Modern and Support Friendly Practice Plugin"
depend:
  - ProtocolLib
softdepend:
  - HolographicDisplays
  - PlaceholderAPI
  - ViaVersion
  - ProtocolSupport
  - MizuCore
  - ZoomCore
  - AquaCore
  - Hestia
  - Scandium
  - nCore
  - PermissionsEx
  - CortexCore
