main: me.drizzy.practice.Array
name: Array
version: Beta 4.3
authors: ["Nick", "Drizzy", "Joeleoli", "veltus5184"]
depend:
  - ProtocolLib
softdepend:
  - HolographicDisplays
  - PlaceholderAPI
  - MizuCore
  - ZoomCore
  - AquaCore
  - Hestia
