main: me.drizzy.practice.Array
name: Array
version: Beta 4.4
authors: ["Tinuy", "Nick"]
credits: ["Drizzy", "Veltus", "Joel"
forked: nPractice (With Permission)
depend:
  - ProtocolLib
softdepend:
  - HolographicDisplays
  - PlaceholderAPI
  - MizuCore
  - ZoomCore
  - AquaCore
  - Hestia
