Mongo:
  Database: Array
  URL: mongodb://127.0.0.1:27017/Array
ARRAY:
  SPAWN: world:108.42862345557752:106.0:2.4753712094583005:-89.59775:0.17956273
Tab:
  Enabled: true
  Color:
    Main: "&b"
    Elements: "&f"
  Header: "&b&lPurge Practice"
  Footer: "&7store.purgemc.club"
Queue-Lore:
- "&7&m----------------------"
- "&fIn Queue &8» &b{in_queue}"
- "&fIn Fight &8» &b{in_fight}"
- ""
- "&bClick to join queue."
- "&7&m----------------------"
performance-mode: true
MOTD:
  enabled: true
  lines:
  - "&7&m------------------------------------------------"
  - "         &b&lPurge Community &7(Practice)"
  - "&7&m------------------------------------------------"
  - "&bPractice Commands:"
  - "&7/duel <Name> &8- &7Send a player a duel request"
  - "&7/spec <Name> &8- &7Spectate a player's ongoing match"
  - "&7/settings &8- &7Edit preferences on the server"
  - "&7/party &8- &7See all party related commands"
  - " "
  - "&7To send a message to your party do &7'&d@&7' <message>:"
  - " "
  - "&bServer Links:"
  - "&7Website &8- &bwww.purgemc.club"
  - "&7Discord &8- &bdiscord.purgemc.club"
  - "&7Store &8- &bstore.purgemc.club"
  - " "
  - "&7Welcome to the &b&lPurge Practice!"
  - "&7&m------------------------------------------------"
Ranked:
  Enabled: true
  Require-Kills: true
  Required-Kills: 10
ELO-Ranks:
  0-991: "Bronze 1"
  992-993: "Bronze 2"
  994-995: "Bronze 3"
  996-997: "Bronze 4"
  998-999: "Bronze 5"
  1000-1010: "Silver 1"
  1011-1020: "Silver 2"
  1021-1030: "Silver 3"
  1031-1040: "Silver 4"
  1041-1050: "Gold 1"
  1051-1060: "Gold 2"
  1061-1070: "Gold 3"
  1071-1080: "Gold 4"
  1081-1150: "Diamond 1"
  1151-1250: "Diamond 2"
  1251-1300: "Diamond 3"
  1301-1350: "Diamond 4"
  1351-1400: "Diamond 5"
  1401-1500: "Prestige"