MONGO:
  DATABASE: "Practice"
  URL: ""
ARRAY:
  SPAWN: world:0.5:101.0:0.5:181.29625:1.3300086
ESSENTIAL:
  Store: 'store.resolve.rip'
#Use Color Codes and Include the & Symbol (Ex: &b)
  Color: '&b'
